### ISSUE TITLE
Add integration with TravisCI

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/email-validation-util#1]
Please configure integration with TravisCI:
* [x] [Enable repo testing in TravisCI](https://travis-ci.org/kpi-web-guild/email-validation-util)
* [x] Add TravisCI badge (master branch) to `README.md` with a single commit. (click ![Build Status](https://travis-ci.org/kpi-web-guild/email-validation-util.svg?branch=master) next to octocat icon on [this page](https://travis-ci.org/kpi-web-guild/email-validation-util))
* [x] Create new branch called `feature/travis-ci-integration` and do all the following steps within that branch.
* [x] Add `.travis.yml` using `nosetests` as a testrunner. Set it up to run Python 3.5 env and add PIP caching. Ensure you install `nose` before running tests:
```yaml
language: python
python: 3.5
cache: pip
before_install: pip install -U nose pre-commit
script: |
  nosetests
  pre-commit run --all-files
```
* [x] Complete unfinished subtasks of #2 
* [x] Push the branch and create a Pull Request for it.
